name: ci

on:
  push:
    branches:
      - 'main'
  # schedule:
  #   - cron: '0 10 * * *'
  # push:
  #   branches:
  #     - '**'
  #   tags:
  #     - 'v*.*.*'
  # pull_request:
  #   branches:
  #     - 'main'

jobs:
  php-fpm-alpine:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx 7.4 dev
        uses: docker/setup-buildx-action@v1
        id: builder1
      -
        name: Set up Docker Buildx 7.4
        uses: docker/setup-buildx-action@v1
        id: builder2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push  7.4 dev
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder1.outputs.name }}
          context: .
          platforms: linux/amd64,linux/arm64
          # platforms: linux/amd64
          cache-from: type=registry,ref=grengojbo/php-fpm-alpine:7.4-dev
          cache-to: type=inline
          push: true
          file: Dockerfile.php-fpm
          target: app-dev # https://github.com/docker/build-push-action/blob/master/docs/advanced/isolated-builders.md
          build-args: COMPOSER_AUTH="{}",APP_BASE_DIR="${{ secrets.APP_BASE_DIR }}",PHP_VERSION="${{ secrets.PHP7_VERSION }}",NEW_UID="${{ secrets.NEW_UID }}"
          tags: |
            grengojbo/php-fpm-alpine:7.4-dev
            ghcr.io/grengojbo/php-fpm-alpine:7.4-dev
      -
        name: Build and push  7.4
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder1.outputs.name }}
          context: .
          platforms: linux/amd64,linux/arm64
          # platforms: linux/amd64
          cache-from: type=registry,ref=grengojbo/php-fpm-alpine:7.4
          cache-to: type=inline
          push: true
          file: Dockerfile.php-fpm
          target: app # https://github.com/docker/build-push-action/blob/master/docs/advanced/isolated-builders.md
          build-args: COMPOSER_AUTH="{}",APP_BASE_DIR="${{ secrets.APP_BASE_DIR }}",PHP_VERSION="${{ secrets.PHP7_VERSION }}",NEW_UID="${{ secrets.NEW_UID }}"
          tags: |
            grengojbo/php-fpm-alpine:7.4
            ghcr.io/grengojbo/php-fpm-alpine:7.4
      # -
      #   name: Update repo description
      #   uses: peter-evans/dockerhub-description@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #     repository: grengojbo/php-fpm-alpine
  php8-fpm-alpine:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx ${{ secrets.PHP8_VERSION }} dev
        uses: docker/setup-buildx-action@v1
        id: builder1
      -
        name: Set up Docker Buildx ${{ secrets.PHP8_VERSION }}
        uses: docker/setup-buildx-action@v1
        id: builder2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push ${{ secrets.PHP8_VERSION }} dev
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder1.outputs.name }}
          context: .
          platforms: linux/amd64,linux/arm64
          # platforms: linux/amd64
          cache-from: type=registry,ref=grengojbo/php-fpm-alpine:${{ secrets.PHP8_VERSION }}-dev
          cache-to: type=inline
          push: true
          file: Dockerfile.php-fpm
          target: app-dev # https://github.com/docker/build-push-action/blob/master/docs/advanced/isolated-builders.md
          build-args: COMPOSER_AUTH="{}",APP_BASE_DIR="${{ secrets.APP_BASE_DIR }}",PHP_VERSION="${{ secrets.PHP8_VERSION }}",NEW_UID="${{ secrets.NEW_UID }}"
          tags: |
            grengojbo/php-fpm-alpine:${{ secrets.PHP8_VERSION }}-dev
            ghcr.io/grengojbo/php-fpm-alpine:${{ secrets.PHP8_VERSION }}-dev
      -
        name: Build and push  ${{ secrets.PHP8_VERSION }}
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder1.outputs.name }}
          context: .
          platforms: linux/amd64,linux/arm64
          # platforms: linux/amd64
          cache-from: type=registry,ref=grengojbo/php-fpm-alpine:${{ secrets.PHP8_VERSION }}
          cache-to: type=inline
          push: true
          file: Dockerfile.php-fpm
          target: app # https://github.com/docker/build-push-action/blob/master/docs/advanced/isolated-builders.md
          build-args: COMPOSER_AUTH="{}",APP_BASE_DIR="${{ secrets.APP_BASE_DIR }}",PHP_VERSION="${{ secrets.PHP8_VERSION }}",NEW_UID="${{ secrets.NEW_UID }}"
          tags: |
            grengojbo/php-fpm-alpine:${{ secrets.PHP8_VERSION }}
            ghcr.io/grengojbo/php-fpm-alpine:${{ secrets.PHP8_VERSION }}